#!/usr/bin/env bash

# Read appearance setting
appearance=$(defaults read NSGlobalDomain AppleInterfaceStyle 2>/dev/null 1>/dev/null && echo "Dark" || echo "Light")

# Read ambient light level
ambientLight=$(./lmutracker)

if [ "${appearance}" == "Light"  ] && [ "${ambientLight}" -le 200000 ]; then
  # Update appearance setting (Light → Dark)
  osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to true'

elif [ "${appearance}" == "Dark" ] && [ "${ambientLight}" -gt 200000 ]; then
  # Update appearance setting (Dark → Light)
  osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to false'
fi
